mqtt:
  host: 192.168.10.73
  user: ha_admin
  password: HK5#R84W$@9nI
ffmpeg:
  hwaccel_args: preset-vaapi
detectors:
  coral:
    type: edgetpu
    device: pci
cameras:
  FrontDoor:
    ffmpeg:
      inputs:
        - path: rtsp://admin:hB!wcZ7tKX9@*pN@192.168.10.51:554/h264Preview_01_sub
          roles: 
            - detect
    detect:
      width: 640
      height: 360
    snapshots:
      enabled: True
    objects:
      track:
       - person
    record:
      enabled: True
      retain:
        days: 30
        mode: motion
      events:
        retain:
          default: 30
          mode: active_objects
  Street:
    ffmpeg:
      inputs:
        - path: rtsp://admin:C%mNgnbw4Rvmk@192.168.10.57:554/h264Preview_01_sub
          roles:
             - detect
    detect:
      width: 640
      height: 360
    snapshots:
      enabled: True
    objects:
      track:
       - person
       - car
    record:
      enabled: True
      retain:
        days: 30
        mode: motion
      events:
        retain:
          default: 30
          mode: active_objects
  Driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:7i$5eq#K#t@192.168.10.52:554/cam/realmonitor?channel=1&subtype=1
          roles:
             - detect
    detect:
      width: 704
      height: 480
    snapshots:
      enabled: True
    objects:
      track:
       - person
    record:
      enabled: True
      retain:
        days: 30
        mode: motion
      events:
        retain:
          default: 30
          mode: active_objects
  Court:
    ffmpeg:
      inputs:
        - path: rtsp://admin:Hytg%45*m2@192.168.10.55:554/h264Preview_01_sub
          roles:
            - detect
    detect:
      width: 640
      height: 360
    snapshots:
      enabled: True
    objects:
      track:
       - person
      filters:
          person:
            threshold: 0.75
    record:
      enabled: True
      retain:
        days: 30
        mode: motion
      events:
        retain:
          default: 30
          mode: active_objects
  AppleTree:
    ffmpeg:
      inputs:
        - path: rtsp://admin:3Yn^a$h3Hc%Lk6@192.168.10.54:554/cam/realmonitor?channel=1&subtype=1
          roles: 
            - detect
    detect:
      width: 704
      height: 480
    snapshots:
      enabled: True
    objects:
      track:
       - person
    record:
      enabled: True
      retain:
        days: 30
        mode: motion
      events:
        retain:
          default: 30
          mode: active_objects
  BackYard:
    ffmpeg:
      inputs:
        - path: rtsp://admin:feNH65b%6*nW@192.168.10.56:554/h264Preview_01_sub
          roles:
            - detect
    detect:
      width: 640
      height: 360
    snapshots:
      enabled: True
    objects:
      track:
       - person
    record:
      enabled: True
      retain:
        days: 30
        mode: motion
      events:
        retain:
          default: 30
